version: "3.3"

services:

        whoami:
                image: "containous/whoami"
                container_name: "simple-service"
                labels:
                        - "traefik.enable=true"
                        - "traefik.http.routers.whoami.rule=Host(`test.${TRAE_DOMAIN_NAME}`)"
                        - "traefik.http.routers.whoami.entrypoints=websecure"
                        - "traefik.http.routers.whoami.tls.certresolver=myresolver"
                        - "traefik.docker.network=web_external"
                networks:
                        - web_external
networks:
        web_external:
                external: true
